### ISSUE TITLE
proper error messages

### ISSUE THREAD

**Issue by cnu** [cnu/godis#6]
Handle errors the golang way.

**Comment by makernaren** [comment]
Have assigned strings as error messages so that the user can compare the 
errors thrown by a command and take decisions based on that. For example if we take RENAME command, before we use to check,

```go
key = mykey
newKey = mykey
got, err := RENAME(key, newKey)
if err != nil {
 // Decide something without knowing exact error
}
```
Now we can check for exact errors,

```go
key = mykey
newKey = mykey
got, err := RENAME(key, newKey)
if err.Error() == "samekeys" {
 // Decide exactly based on error thrown
}
```
